schema_version: 1

context:
  version: "0.2.0"

package:
  name: r-aniprocess
  version: ${{ version }}

source:
  url: https://animovement.r-universe.dev/src/contrib/aniprocess_${{ version }}.tar.gz
  sha256: ccb1135266668562ac127ddc045b0b0915849f249c3d91d908a8b8f896b11f5c

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --no-multiarch --with-keep.source .

requirements:
  host:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-collapse
    - r-dplyr
    - r-rlang
  run:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-collapse
    - r-dplyr
    - r-rlang

tests:
  - script:
      - Rscript -e "library(aniprocess)"

about:
  homepage: https://github.com/animovement/aniprocess
  summary: An R package for signal processing and filtering of movement data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
