schema_version: 1

context:
  version: "0.5.0"

package:
  name: r-aniframe
  version: ${{ version }}

source:
  url: https://animovement.r-universe.dev/src/contrib/aniframe_${{ version }}.tar.gz
  sha256: 88c0506c58dd1f4134a650919f6501e7c7623c024aad72234fafe0231bd218d4

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --no-multiarch --with-keep.source .

requirements:
  host:
    - r-base >=4.1.0
    - r-cli
    - r-dplyr
    - r-rlang
    - r-pillar
    - r-anytime
  run:
    - r-base >=4.1.0
    - r-cli
    - r-dplyr
    - r-rlang
    - r-pillar
    - r-anytime

tests:
  - script:
      - Rscript -e "library(aniframe)"

about:
  homepage: https://github.com/animovement/aniframe
  summary: An R package providing core data structures for movement data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
