schema_version: 1

context:
  version: "0.4.0"

package:
  name: r-aniread
  version: ${{ version }}

source:
  url: https://animovement.r-universe.dev/src/contrib/aniread_${{ version }}.tar.gz
  sha256: b5f66240415e9ff86d21b3ee0fb873e76f89a66d75c1d642b9b2138927d5c01c

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --no-multiarch --with-keep.source .

requirements:
  host:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-janitor
    - r-rlang
    - r-stringr
    - r-tidyr
    - r-tidyselect
    - r-vroom
  run:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-janitor
    - r-rlang
    - r-stringr
    - r-tidyr
    - r-tidyselect
    - r-vroom

tests:
  - script:
      - Rscript -e "library(aniread)"

about:
  homepage: https://github.com/animovement/aniread
  summary: An R package for reading and writing movement data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
