schema_version: 1

context:
  version: "0.2.0"
  python_min: "3.11"

package:
  name: pixiline
  version: ${{ version }}

source:
  url: https://github.com/roaldarbol/pixiline/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 87d2f7832892320ab9373609403887dc8b2cbd9ad5b40c97b8d4499c9aed481d

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - pixiline = pixiline.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pyside6 >=6.7
    - loguru >=0.7
    - pyte
    - pixi
    - menuinst >=2

tests:
  - python:
      imports:
        - pixiline
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/roaldarbol/pixiline
  repository: https://github.com/roaldarbol/pixiline
  summary: A generic Pixi-pipeline manager GUI.
  description: |
    pixiline is a thin PySide6 front-end for running and orchestrating
    pixi-based pipelines. It builds and runs `pixi run ...` commands and
    provides a queued job system with a DAG view of pipeline stages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
